/* ───────────────────────────────────────────────────────────────────────────
   Mock data — mirrors /public/datas/*.ts and is consumed by api.js.
   Replace these with real API responses when wiring up the backend.
   ─────────────────────────────────────────────────────────────────────────── */

const siteConfig = {
  name: "yumi",
  topBanner: "Free shipping on all U.S. orders $50+",
  navLinks: [
    { name: "Home", href: "/" },
    { name: "Shop", href: "/shop" },
    { name: "About", href: "/about" },
    { name: "Contact", href: "/contact" },
  ],
  featuredProducts: {
    title: "Our Featured Products",
    subtitle: "Get the skin you want to feel",
  },
};

const heroSlides = [
  {
    id: 1,
    subtitle: "ESSENSTIAL ITEMS",
    title: "Beauty Inspired by Real Life",
    description: "Made using clean, non-toxic ingredients, our products are designed for everyone.",
    buttonText: "Shop Now",
    buttonLink: "/shop",
    backgroundImage: "https://picsum.photos/1920/1080?random=101",
    mobileImage: "https://picsum.photos/600/900?random=101",
  },
  {
    id: 2,
    subtitle: "NEW ARRIVALS",
    title: "Pure Glow for Your Skin",
    description: "Discover our latest collection of organic skincare products.",
    buttonText: "Explore Now",
    buttonLink: "/shop",
    backgroundImage: "https://picsum.photos/1920/1080?random=102",
    mobileImage: "https://picsum.photos/600/900?random=102",
  },
  {
    id: 3,
    subtitle: "SUMMER SALE",
    title: "Refresh Your Routine",
    description: "Up to 30% off on all facial oils and cleansers this summer.",
    buttonText: "Shop Sale",
    buttonLink: "/shop",
    backgroundImage: "https://picsum.photos/1920/1080?random=103",
    mobileImage: "https://picsum.photos/600/900?random=103",
  },
];

const promoBanners = [
  {
    id: 1,
    subtitle: "NEW COLLECTION",
    title: "Intensive Glow C+ Serum",
    buttonText: "Explore More",
    buttonLink: "/shop",
    image: "https://picsum.photos/1000/1000?random=104",
    bgColor: "bg-[#F8F8F8]",
  },
  {
    id: 2,
    title: "25% off Everything",
    description: "Makeup with extended range in colors for every human.",
    buttonText: "Shop Sale",
    buttonLink: "/shop",
    image: "https://picsum.photos/1000/1000?random=105",
    bgColor: "bg-[#CCDCD2]",
  },
];

const discoveryData = {
  heading: "More to Discover",
  description: "Our bundles were designed to conveniently package your tanning essentials while saving you money.",
  items: [
    {
      id: 1,
      title: "Summer Collection",
      linkText: "Shop Now",
      linkUrl: "/shop",
      image: "https://picsum.photos/1000/1000?random=106",
    },
    {
      id: 2,
      title: "From Our Blog",
      linkText: "Read More",
      linkUrl: "/blog",
      image: "https://picsum.photos/1000/1000?random=107",
    },
  ],
};

const contactData = {
  header: {
    title: "Keep In Touch with Us",
    description: "We're talking about clean beauty gift sets, of course – and we've got a bouquet of beauties for yourself or someone you love.",
  },
  address: {
    title: "Address",
    lines: [
      "3245 Abbot Kinney BLVD -",
      "PH Venice, CA 124",
      "76 East Houston Street",
      "New York City",
    ],
    directionLink: "#",
  },
  contact: {
    title: "Contact",
    mobile: "068 26589 996",
    hotline: "1900 26886",
    email: "hello@grace.com",
  },
  hours: {
    title: "Hour of operation",
    items: [
      { label: "Mon - Fri:", value: "08:30 – 20:00" },
      { label: "Sat & Sun:", value: "09:30 – 21:30" },
    ],
  },
  form: {
    title: "Send A Message",
    placeholders: {
      name: "Name",
      email: "Email",
      phone: "Phone Number",
      message: "Message",
    },
    buttonText: "Submit",
  },
};

const privacyPolicyData = {
  title: "Privacy Policy",
  lastUpdated: "January 20, 2026",
  sections: [
    {
      title: "1. Information We Collect",
      content: "We collect information you provide directly to us, such as when you create an account, make a purchase, or contact us. This may include your name, email address, phone number, and shipping address.",
    },
    {
      title: "2. How We Use Your Information",
      content: "We use the information we collect to provide, maintain, and improve our services, process transactions, and communicate with you about your orders and promotional offers.",
    },
    {
      title: "3. Information Sharing",
      content: "We do not sell your personal information. We may share information with third-party service providers who perform services on our behalf, such as payment processing and shipping.",
    },
  ],
};

const termsConditionsData = {
  title: "Terms & Conditions",
  lastUpdated: "January 20, 2026",
  sections: [
    {
      title: "1. Acceptance of Terms",
      content: "By accessing and using this website, you agree to be bound by these Terms and Conditions and all applicable laws and regulations.",
    },
    {
      title: "2. Product Information",
      content: "We attempt to be as accurate as possible in describing our products. However, we do not warrant that product descriptions or other content are accurate, complete, reliable, or error-free.",
    },
    {
      title: "3. Shipping & Returns",
      content: "Please refer to our Shipping and Returns policy for detailed information about our delivery process and how to return items.",
    },
  ],
};

const faqData = {
  title: "Frequently Asked Questions",
  description: "Find answers to the most common questions about our products, shipping, and more.",
  categories: [
    {
      name: "Orders & Shipping",
      questions: [
        {
          id: 1,
          question: "How long does shipping take?",
          answer: "Standard shipping typically takes 3-5 business days within the continental US.",
        },
        {
          id: 2,
          question: "Do you ship internationally?",
          answer: "Yes, we ship to most countries worldwide. International shipping times vary by location.",
        },
        {
          id: 3,
          question: "Are your products organic?",
          answer: "Yes, all our products are made with 100% organic and ethically sourced ingredients.",
        },
        {
          id: 4,
          question: "What is your return policy?",
          answer: "We offer a 30-day money-back guarantee on all unopened products.",
        },
      ],
    },
  ],
};

const aboutData = {
  hero: {
    subtitle: "INTRODUCING",
    title: "About Glowing",
    backgroundImage: "https://picsum.photos/1920/1080?random=301",
  },
  missionStatement: {
    icon: "/leaf-icon.png",
    title: "We strive to live with compassion, kindness and empathy",
    description: "A lot of so-called stretch denim pants out there are just glorified sweatpants – they get baggy and lose their shape. Not cool. Our tightly knitted fabric holds its form after repeated wear. Plus, Aldays dress up or down, no prob. So you can wear them all day. Get it?",
  },
  sections: [
    {
      id: 1,
      title: "Give your skin a healthy glow everyone",
      description: "Luxe, lightweight, and made with the perfect blend of cashmere and cotton, our Sonoma Pillows and Throws are inspired by the basics we turn to season after season. Get to know the cozy essentials that will elevate your space in an instant.",
      image: "https://picsum.photos/1000/1000?random=302",
      imagePosition: "left",
    },
    {
      id: 2,
      title: "Our misstion",
      description: "Luxe, lightweight, and made with the perfect blend of cashmere and cotton, our Sonoma Pillows and Throws are inspired by the basics we turn to season after season. Get to know the cozy essentials that will elevate your space in an instant.",
      image: "https://picsum.photos/1000/1000?random=303",
      imagePosition: "right",
    },
  ],
};

const footerData = {
  company: {
    title: "Company",
    description: "Find a location nearest you.",
    phone: "+391 (0)35 2568 4593",
    email: "hello@domain.com",
    storeLink: "/stores",
  },
  usefulLinks: {
    title: "Useful Links",
    links: [
      { label: "Home", href: "/" },
      { label: "Shop", href: "/shop" },
      { label: "About Us", href: "/about" },
      { label: "Blogs", href: "/blog" },
      { label: "Contact", href: "/contact" },
    ],
  },
  information: {
    title: "Infomation",
    links: [
      { label: "FAQ", href: "/faq" },
      { label: "Terms & Conditions", href: "/terms-conditions" },
      { label: "Privacy Policy", href: "/privacy-policy" },
    ],
  },
  newsletter: {
    title: "Good emails.",
    description: "Enter your email below to be the first to know about new collections and product launches.",
    placeholder: "Enter your email address",
    buttonText: "Subscribe",
  },
  logo: "YUMI",
  socials: [
    { platform: "instagram", href: "https://instagram.com" },
    { platform: "facebook", href: "https://facebook.com" },
    { platform: "tiktok", href: "https://tiktok.com" },
  ],
};

const products = [
  {
    id: 1,
    name: "Film Eyeshadow",
    category: "Lip Gloss",
    price: 23.0,
    oldPrice: 27.0,
    image: "https://picsum.photos/800/1000?random=1",
    badge: "Sale",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut. Eu agam malorum nec. Eu has vide putent, dico option nominati no eam. Ea erant impetus consequuntur eos, velit congue vidisse eos ne.",
    slug: "film-eyeshadow",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Cosmetic", "Make Up"],
    gallery: ["https://picsum.photos/800/1000?random=1", "https://picsum.photos/800/1000?random=101", "https://picsum.photos/800/1000?random=201"],
    variantType: "Colors",
    variants: [
      { name: "Classic Pink", image: "https://picsum.photos/800/1000?random=1", gallery: ["https://picsum.photos/800/1000?random=1", "https://picsum.photos/800/1000?random=101", "https://picsum.photos/800/1000?random=201"] },
      { name: "Velvet Red", image: "https://picsum.photos/800/1000?random=2", gallery: ["https://picsum.photos/800/1000?random=2", "https://picsum.photos/800/1000?random=102", "https://picsum.photos/800/1000?random=202"] },
      { name: "Deep Ocean", image: "https://picsum.photos/800/1000?random=3", gallery: ["https://picsum.photos/800/1000?random=3", "https://picsum.photos/800/1000?random=103", "https://picsum.photos/800/1000?random=203"] },
    ],
    videos: ["EngW7tLk6R8", "a3ICNMQW7Ok"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 2,
    name: "WILD PALETTES",
    category: "Lip Gloss",
    price: 25.0,
    image: "https://picsum.photos/800/1000?random=4",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut. Eu agam malorum nec. Eu has vide putent, dico option nominati no eam.",
    slug: "wild-palettes",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Cosmetic", "Palettes"],
    gallery: ["https://picsum.photos/800/1000?random=4", "https://picsum.photos/800/1000?random=104", "https://picsum.photos/800/1000?random=204"],
    variantType: "Colors",
    variants: [
      { name: "Forest Green", image: "https://picsum.photos/800/1000?random=4", gallery: ["https://picsum.photos/800/1000?random=4", "https://picsum.photos/800/1000?random=104"] },
      { name: "Earth Brown", image: "https://picsum.photos/800/1000?random=5", gallery: ["https://picsum.photos/800/1000?random=5", "https://picsum.photos/800/1000?random=105"] },
    ],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 3,
    name: "ROSE SAFARI",
    category: "Lip Gloss",
    price: 35.0,
    image: "https://picsum.photos/800/1000?random=6",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut. Eu agam malorum nec.",
    slug: "rose-safari",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Classic", "Lipstick"],
    gallery: ["https://picsum.photos/800/1000?random=6", "https://picsum.photos/800/1000?random=106", "https://picsum.photos/800/1000?random=206"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 4,
    name: "SUMMER MIRAGE",
    category: "Lip Gloss",
    price: 32.0,
    image: "https://picsum.photos/800/1000?random=7",
    badge: "New",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "summer-mirage",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Summer", "Limited"],
    gallery: ["https://picsum.photos/800/1000?random=7", "https://picsum.photos/800/1000?random=107", "https://picsum.photos/800/1000?random=207"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 5,
    name: "SUMMER DRAMA",
    category: "Lip Gloss",
    price: 32.0,
    image: "https://picsum.photos/800/1000?random=8",
    badge: "New",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "summer-drama",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Drama", "Intense"],
    gallery: ["https://picsum.photos/800/1000?random=8", "https://picsum.photos/800/1000?random=108", "https://picsum.photos/800/1000?random=208"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 6,
    name: "VELVET MATTE",
    category: "Lipstick",
    price: 18.0,
    image: "https://picsum.photos/800/1000?random=9",
    badge: "Sale",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "velvet-matte",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Matte", "Velvet"],
    gallery: ["https://picsum.photos/800/1000?random=9", "https://picsum.photos/800/1000?random=109", "https://picsum.photos/800/1000?random=209"],
    variantType: "Shades",
    variants: [
      { name: "Nude 01", image: "https://picsum.photos/800/1000?random=9", gallery: ["https://picsum.photos/800/1000?random=9", "https://picsum.photos/800/1000?random=109"] },
      { name: "Rose 02", image: "https://picsum.photos/800/1000?random=10", gallery: ["https://picsum.photos/800/1000?random=10", "https://picsum.photos/800/1000?random=110"] },
    ],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 7,
    name: "GLOW SERUM",
    category: "Skin Care",
    price: 45.0,
    image: "https://picsum.photos/800/1000?random=11",
    badge: "New",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "glow-serum",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Serum", "Glow"],
    gallery: ["https://picsum.photos/800/1000?random=11", "https://picsum.photos/800/1000?random=111", "https://picsum.photos/800/1000?random=211"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: false,
  },
  {
    id: 8,
    name: "SILK FOUNDATION",
    category: "Skin Care",
    price: 38.0,
    image: "https://picsum.photos/800/1000?random=12",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "silk-foundation",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Foundation", "Silk"],
    gallery: ["https://picsum.photos/800/1000?random=12", "https://picsum.photos/800/1000?random=112", "https://picsum.photos/800/1000?random=212"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: false,
  },
  {
    id: 9,
    name: "EYELASH CURLER",
    category: "Eye Care",
    price: 12.0,
    image: "https://picsum.photos/800/1000?random=13",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "eyelash-curler",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Tools", "Curler"],
    gallery: ["https://picsum.photos/800/1000?random=13", "https://picsum.photos/800/1000?random=113", "https://picsum.photos/800/1000?random=213"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 10,
    name: "BROW GEL",
    category: "Eye Care",
    price: 15.0,
    image: "https://picsum.photos/800/1000?random=14",
    badge: "New",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "brow-gel",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Brows", "Gel"],
    gallery: ["https://picsum.photos/800/1000?random=14", "https://picsum.photos/800/1000?random=114", "https://picsum.photos/800/1000?random=214"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: false,
  },
  {
    id: 11,
    name: "PEACH BLUSH",
    category: "Cheek",
    price: 22.0,
    image: "https://picsum.photos/800/1000?random=15",
    badge: "Sale",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "peach-blush",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Blush", "Peach"],
    gallery: ["https://picsum.photos/800/1000?random=15", "https://picsum.photos/800/1000?random=115", "https://picsum.photos/800/1000?random=215"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: true,
  },
  {
    id: 12,
    name: "MATTE BRONZER",
    category: "Cheek",
    price: 28.0,
    image: "https://picsum.photos/800/1000?random=16",
    description: "An dico accommodare ius, porro mnesarchum pro in. Cetero fierent urbanitas eam id, sed movet voluptua ut.",
    slug: "matte-bronzer",
    shortDescription: "Clean, lightweight and skin-loving — made for an effortless everyday glow.",
    longDescription: "Write the full product story here. Describe the texture, the key ingredients, how to apply it and the results your customers can expect. This longer description gives shoppers the detail they need before adding it to their routine.",
    tags: ["Bronzer", "Matte"],
    gallery: ["https://picsum.photos/800/1000?random=16", "https://picsum.photos/800/1000?random=116", "https://picsum.photos/800/1000?random=216"],
    videos: ["vP9X2V9c3Uw"],
    purchaseLink: "#",
    featured: false,
  },
];

const blogs = [
  {
    id: 1,
    slug: "the-cosmetics-world",
    category: "Lipstick",
    author: "Janny Joe",
    day: "08",
    month: "Apr",
    title: "THE COSMETICS WORLD",
    excerpt: "Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei.Et ...",
    description: "Lorem ipsum dolor sit amet, odio legere cotidieque ex quo, an noster evertitur vel, ei solet democritum est. Id mel tibique ancillae convenire. Admodum tacimates maiestatis his id. Sed everti accusamus facilisi ne. Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei. Et qui falli latine consequuntur. In appellantur concludaturque pro. Commune scriptorem ad pri, ut euripidis posidonium has. Eum ei verear dolorum. Duo quas viris delenit cu, dolores inciderint scribentur mel in. Option elaboraret et mea, sea eligendi insolens scripserit et, tantas assueverit liberavisse vim at. Prima modus erroribus id cum, te mea munere doming equidem. At per ullum facilisis. Lorem ipsum dolor sit amet, ceteros temporibus mei ad, eum Mel purto adipisci eu, ex eum nisl consul, has virtute inermis ne. Eripxit delicatissimi in eos. Pri ut congue dolorem. Impetus consequat in qui, pro posse bonorum delicatissimi ad, veri voluptatibus ei qui. Munere accusamus ex has, pri vero populo voluptaria eum no, eos atomoru.",
    image: "https://picsum.photos/1200/800?random=201",
    isFeatured: true,
  },
  {
    id: 2,
    slug: "prep-a-good-primer",
    category: "Lipstick",
    author: "Janny Joe",
    day: "09",
    month: "Apr",
    title: "PREP A GOOD PRIMER",
    excerpt: "Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei.Et ...",
    description: "Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei. Et qui falli latine consequuntur. In appellantur concludaturque pro. Commune scriptorem ad pri, ut euripidis posidonium has. Eum ei verear dolorum. Duo quas viris delenit cu, dolores inciderint scribentur mel in. Option elaboraret et mea, sea eligendi insolens scripserit et, tantas assueverit liberavisse vim at. Prima modus erroribus id cum, te mea munere doming equidem. At per ullum facilisis. Lorem ipsum dolor sit amet, ceteros temporibus mei ad, eum Mel purto adipisci eu, ex eum nisl consul, has virtute inermis ne. Eripxit delicatissimi in eos. Pri ut congue dolorem. Impetus consequat in qui, pro posse bonorum delicatissimi ad, veri voluptatibus ei qui. Munere accusamus ex has, pri vero populo voluptaria eum no, eos atomoru.",
    image: "https://picsum.photos/1200/800?random=202",
    isFeatured: true,
  },
  {
    id: 3,
    slug: "know-how-to-apply-it",
    category: "Lipstick",
    author: "Janny Joe",
    day: "08",
    month: "Apr",
    title: "KNOW HOW TO APPLY IT",
    excerpt: "Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei.Et ...",
    description: "Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei. Et qui falli latine consequuntur. In appellantur concludaturque pro. Commune scriptorem ad pri, ut euripidis posidonium has. Eum ei verear dolorum. Duo quas viris delenit cu, dolores inciderint scribentur mel in. Option elaboraret et mea, sea eligendi insolens scripserit et, tantas assueverit liberavisse vim at. Prima modus erroribus id cum, te mea munere doming equidem. At per ullum facilisis. Lorem ipsum dolor sit amet, ceteros temporibus mei ad, eum Mel purto adipisci eu, ex eum nisl consul, has virtute inermis ne. Eripxit delicatissimi in eos. Pri ut congue dolorem. Impetus consequat in qui, pro posse bonorum delicatissimi ad, veri voluptatibus ei qui. Munere accusamus ex has, pri vero populo voluptaria eum no, eos atomoru.",
    image: "https://picsum.photos/1200/800?random=203",
  },
  {
    id: 4,
    slug: "50-shades-of-great",
    category: "idk",
    author: "Tashdid",
    day: "08",
    month: "Apr",
    title: "50 SHADES OF GREAT",
    excerpt: "Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei.Et ...",
    description: "Est diam debitis an, error recusabo id pro, quo eripuit civibus ut. Mel ut tamquam erroribus, ad nonumy vituperata mei. Et qui falli latine consequuntur. In appellantur concludaturque pro. Commune scriptorem ad pri, ut euripidis posidonium has. Eum ei verear dolorum. Duo quas viris delenit cu, dolores inciderint scribentur mel in. Option elaboraret et mea, sea eligendi insolens scripserit et, tantas assueverit liberavisse vim at. Prima modus erroribus id cum, te mea munere doming equidem. At per ullum facilisis. Lorem ipsum dolor sit amet, ceteros temporibus mei ad, eum Mel purto adipisci eu, ex eum nisl consul, has virtute inermis ne. Eripxit delicatissimi in eos. Pri ut congue dolorem. Impetus consequat in qui, pro posse bonorum delicatissimi ad, veri voluptatibus ei qui. Munere accusamus ex has, pri vero populo voluptaria eum no, eos atomoru.",
    image: "https://picsum.photos/1200/800?random=204",
  },
  {
    id: 5,
    slug: "summer-skincare-routine",
    category: "Skincare",
    author: "Elena Rose",
    day: "12",
    month: "May",
    title: "SUMMER SKINCARE ROUTINE",
    excerpt: "Discover the essential steps to keep your skin glowing and protected during the hot summer months with our expert tips...",
    description: "As the temperature rises, your skin's needs change. This guide covers everything from lightweight hydration to the importance of SPF reapplication. We dive deep into the best ingredients for summer, such as Vitamin C for antioxidant protection and Hyaluronic Acid for oil-free moisture. Learn how to transition your heavy winter creams to breezy summer serums without losing that healthy glow. Our routine is designed for all skin types, focusing on maintaining a balanced barrier while dealing with increased sweat and sebum production.",
    image: "https://picsum.photos/1200/800?random=205",
    isFeatured: true,
  },
  {
    id: 6,
    slug: "art-of-perfect-eyeliner-test",
    category: "Eyes",
    author: "Marco V",
    day: "02",
    month: "Jun",
    title: "ART OF PERFECT EYELINER",
    excerpt: "Master the wing with our comprehensive guide to eyeliner techniques, from classic pencils to sharp liquid finishes...",
    description: "Whether you prefer a subtle tightline or a bold dramatic wing, mastering eyeliner is a fundamental skill for any makeup enthusiast. In this post, Marco V shares professional secrets for steadying your hand, choosing the right formula for your eye shape, and the absolute best tools for the job. We explore the history of the cat-eye and provide a step-by-step tutorial for three versatile looks that transition perfectly from day to night. Stop struggling with uneven lines and start creating art on your eyelids.",
    image: "https://picsum.photos/1200/800?random=206",
  },
  {
    id: 7,
    slug: "premium-feather-light-lipstick",
    category: "Lipstick",
    author: "Faria",
    day: "04",
    month: "Jun",
    title: "Premium feather-light, comfortable lipstick",
    excerpt: "Distinctively reconceptualize resource maximizing methodologies for enterprise strategic theme areas. Energistically revolutionize high standards in e-tailers without principle-centered scenarios. Efficiently evolve B2C solutions vis-a-vis...",
    description: "Experience the ultimate in lip comfort with our new feather-light formula. Designed for all-day wear without drying, this lipstick provides a rich pigment while feeling weightless on your lips. Perfect for both professional settings and casual outings.",
    image: "https://picsum.photos/1200/800?random=207",
  },
  {
    id: 8,
    slug: "long-lasting-nail-polish",
    category: "Nails",
    author: "Faria",
    day: "12",
    month: "Jun",
    title: "Long-lasting & quick dry nail polish set",
    excerpt: "Distinctively reconceptualize resource maximizing methodologies for enterprise strategic theme areas. Energistically revolutionize high standards in e-tailers without principle-centered scenarios. Efficiently evolve B2C solutions vis-a-vis...",
    description: "Our quick-dry nail polish set is a game-changer for those on the go. Get salon-quality results at home with a formula that stays chip-free for up to two weeks. Available in a variety of vibrant spring and summer shades.",
    image: "https://picsum.photos/1200/800?random=208",
  },
  {
    id: 9,
    slug: "glow-from-within",
    category: "Serum",
    author: "Sarah J",
    day: "15",
    month: "Jul",
    title: "How to get the perfect glow from within",
    excerpt: "Discover the secrets of internal hydration and the specific vitamins that help your skin shine from the inside out...",
    description: "Skin health starts deep within. In this article, we explore how diet, hydration, and supplements can transform your complexion more than any topical product. We speak with dermatologists to understand the link between gut health and skin clarity.",
    image: "https://picsum.photos/1200/800?random=209",
  },
  {
    id: 10,
    slug: "sustainable-beauty-packaging",
    category: "Eco",
    author: "Eco Team",
    day: "22",
    month: "Aug",
    title: "The future of sustainable beauty packaging",
    excerpt: "Why we are moving towards 100% recyclable materials and what it means for the beauty industry at large...",
    description: "Packaging waste is a major concern in the cosmetics world. Lily & Lavender is taking steps to ensure all our bottles and jars are made from post-consumer recycled plastic. Read about our journey towards a zero-waste future.",
    image: "https://picsum.photos/1200/800?random=210",
  },
  {
    id: 11,
    slug: "organic-ingredients-matter",
    category: "Organic",
    author: "Nature Guy",
    day: "01",
    month: "Sep",
    title: "Why organic ingredients actually matter",
    excerpt: "Breaking down the science behind organic vs synthetic ingredients in your daily skincare routine...",
    description: "Not all natural ingredients are created equal. We look at the certification process for organic farming and why these ingredients are often more potent and less irritating for sensitive skin. Join us as we visit our organic source farms.",
    image: "https://picsum.photos/1200/800?random=211",
  },
  {
    id: 12,
    slug: "minimalist-makeup-routine",
    category: "Routine",
    author: "Minimalist",
    day: "10",
    month: "Oct",
    title: "A 5-minute minimalist makeup routine",
    excerpt: "For the busy soul who wants to look put together without spending hours in front of the mirror every morning...",
    description: "Less is more. We demonstrate how just four multi-purpose products can create a full, polished look. Perfect for travel, gym, or just a lazy Sunday morning. Focus on enhancing your natural features efficiently.",
    image: "https://picsum.photos/1200/800?random=212",
  },
  {
    id: 12,
    slug: "minimalist-makeup-routine",
    category: "Routine",
    author: "Minimalist",
    day: "10",
    month: "Oct",
    title: "A 5-minute minimalist makeup routine",
    excerpt: "For the busy soul who wants to look put together without spending hours in front of the mirror every morning...",
    description: "Less is more. We demonstrate how just four multi-purpose products can create a full, polished look. Perfect for travel, gym, or just a lazy Sunday morning. Focus on enhancing your natural features efficiently.",
    image: "https://picsum.photos/1200/800?random=212",
  },
];
